### ISSUE TITLE
categorical metadata group checkbox not working right

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#432]
Each categorical metadata group has a group checkbox (in addition to the checkbox for each metadata option).

Example: group 'louvain' has a checkbox, as do each cluster within.

The group checkbox is supposed to be tri-state (all selected, non-selected, some selected), but doesn't correctly work.

Test case:
1. load a data set
2. open a group so you see all the options
3. deselect one item in the group
--at this point the group checkbox correctly shows mixed state
4. click the group checkbox - it should either switch to all or none selected, but instead stays in "some selected" state.
5. Now select all categories in the group - the group checkbox does not switch back to "all selected"

etc.

**Comment by neuromusic** [comment]
this appears fixed in 0.2.6. closing.

**Comment by bkmartinjr** [comment]
This issue is not fixed - reopening.

Another test case:
1. Load pbcm3k test data set
2. open louvain metadata group 
3. click the *group* (louvain) checkbox so that all values are deselected.
4. select each value individually, ie, select B cells, then CD14+, etc, continuing until all are selected

At this point, the *group* checkbox should be in a selected state, but it is not.   

Screen grab:
![image](https://user-images.githubusercontent.com/3740062/50045878-4285eb80-004f-11e9-969f-ecd9ff2c362b.png)

**Comment by neuromusic** [comment]
thanks @bkmartinjr. once I figure out my problems with #515 I should be able to work on master again.
